apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: dummy
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "k8s"
spec:
  dummy:
    rate: 1 #Events number generated per second
    tag: my_dummy
    dummy: {"message":"fluent-operator walkthrough"}