apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: kubelet
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  dummy:
    rate: 1 #Events number generated per second
    tag: my_dummy
    dummy: {"message":"fluent-operator walkthrough"}